[package]
name = "blosc2-rs"
version = "0.2.0+2.13.2"
edition = "2021"

[lib]
name = "blosc2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blosc2-sys = { path = "blosc2-sys" }
parking_lot = "^0.12"

[dev-dependencies]
ctor = "0.2.0"
criterion = { version = "0.4", features = ["html_reports"] }
rand = "*"

[[bench]]
name = "benchmarks"
harness = false
