[package]
name = "blosc2-rs"
version = "0.1.0+2.8.0"
edition = "2021"

[lib]
name = "blosc2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blosc2-sys = { path = "blosc2-sys" }

[dev-dependencies]
ctor = "0.2.0"
criterion = { version = "0.4", features = ["html_reports"] }
rand = "*"

[[bench]]
name = "benchmarks"
harness = false
