[package]
name = "blosc2-sys"
version = "0.2.3+2.14.0"
edition = "2021"
description = "Bindings to C Blosc2"
license = "MIT"
links = "blosc2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
defaults = []
use-system-blosc2 = []
static = []

[build-dependencies]
cmake = "^0.1"
bindgen = "^0.64"
pkg-config = "^0.3"
