name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - released
      - prereleased

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13  # x86_64
          - macos-14  # M1
          - windows-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install packages (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)" >> $GITHUB_ENV
          brew install ninja

      - name: Install packages (Windows)
        if: runner.os == 'Windows'
        run: choco install ninja

      - name: Install packages (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt update

      - uses: rui314/setup-mold@v1

      - name: Build
        run: cargo build
        env:
          CC: clang
          CFLAGS: ""
          LDFLAGS: ""
          CI: true

      - name: Test
        run: cargo test
        env:
          CC: clang
          CFLAGS: ""
          LDFLAGS: ""
          CI: true
