name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - released
      - prereleased

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test

  windows:
    runs-on: windows-latest
    # TODO: https://github.com/rust-lang/rust-bindgen/issues/2179
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
