name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - released
      - prereleased

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    matrix:
      os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          enviornment-name: blosc2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --features use-system-blosc2
      - name: Test
        run: cargo test --features use-system-blosc2
