name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - released
      - prereleased

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test -- --test-threads 1

  windows:
    runs-on: windows-latest
    # TODO: https://github.com/rust-lang/rust-bindgen/issues/2179
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-pc-windows-gnu"
      - name: Build
        run: cargo build --target x86_64-pc-windows-gnu
      - name: Test
        run: cargo test --target x86_64-pc-windows-gnu

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
